apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "rbk8s-8017"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "rbk8s-8017"
    spec:
      containers:
        - name: "rbk8s-8017"
          image: "rachitbacr.azurecr.io/rbk8s"
          ports:
          - containerPort: 3000