apiVersion: v1
kind: Service
metadata:
    name: "rbk8s-8017"
    labels:
        app: "rbk8s-8017"
spec:
    type: LoadBalancer
    ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
    selector:
        app: "rbk8s-8017"